#房源推荐算法——基于 Airbnb 北京房价预测的机器学习模型
#第14组
#by 何智钧

#Linear Regressions
#2021-01-06
#统一改为无截距回归
#聚类2

#导入第三方库
import pandas as pd
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm
import statsmodels.formula.api as smf

#读取listing.csv并简要查看文件内容
listing_data2=pd.read_excel("E:/钧资料3/大学资料/课程/LN3125数据挖掘与机器学习/final project/beijing1026/listings/listings_clusters1211.xlsx",sheet_name="聚类2",header=0,names=None,verbose=True,engine="openpyxl")
print(listing_data2)
print(listing_data2.describe())
print(listing_data2.info())
print(listing_data2.dtypes)
print(listing_data2.shape)
for label in listing_data2.columns:
    print(label)
    #print(listing_data2[[label]].head(5))
    #print("Missing values: {}".format(listing_data2[[label]].isnull().sum()))
    #print("\n\n")

#定义自变量和因变量的名字
X_names=["host_time",
                #"first_review_to_today",
                #"last_review_to_today",
                "num_of_host_verifications",
                "num_of_amenities",
                "latitude",
                "longitude",
                "host_response_rate",
                "host_acceptance_rate",
                "host_listings_count",
                "accommodates",
                "bathrooms",
                "bedrooms",
                "beds",
                "minimum_nights",
                "maximum_nights",
                "availability_30",
                "availability_60",
                "availability_90",
                "availability_365",
                "number_of_reviews",
                "number_of_reviews_ltm",
                #"review_scores_rating",
                #"review_scores_accuracy",
                #"review_scores_cleanliness",
                #"review_scores_checkin",
                #"review_scores_communication",
                #"review_scores_location",
                #"review_scores_value",
                "calculated_host_listings_count",
                "calculated_host_listings_count_entire_homes",
                "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms",
                #"reviews_per_month",
                "host_response_time_a few days or more",
                "host_response_time_within a day",
                "host_response_time_within a few hours",
                "host_response_time_within an hour",
                "host_is_superhost_t",
                "host_is_superhost_f",
                "host_has_profile_pic_t",
                "host_has_profile_pic_f",
                "host_identity_verified_t",
                "host_identity_verified_f",
                "property_type_Barn",
                "property_type_Camper/RV",
                "property_type_Campsite",
                "property_type_Casa particular",
                "property_type_Castle",
                "property_type_Cave",
                "property_type_Dome house",
                "property_type_Earth house",
                "property_type_Entire apartment",
                "property_type_Entire bed and breakfast",
                "property_type_Entire bungalow",
                "property_type_Entire cabin",
                "property_type_Entire chalet",
                "property_type_Entire condominium",
                "property_type_Entire cottage",
                "property_type_Entire guest suite",
                "property_type_Entire guesthouse",
                "property_type_Entire home/apt",
                "property_type_Entire house",
                "property_type_Entire loft",
                "property_type_Entire place",
                "property_type_Entire resort",
                "property_type_Entire serviced apartment",
                "property_type_Entire townhouse",
                "property_type_Entire villa",
                "property_type_Farm stay",
                "property_type_Houseboat",
                "property_type_Hut",
                "property_type_Igloo",
                "property_type_Kezhan",
                "property_type_Minsu",
                "property_type_Pension",
                "property_type_Private room",
                "property_type_Private room in apartment",
                "property_type_Private room in barn",
                "property_type_Private room in bed and breakfast",
                "property_type_Private room in bungalow",
                "property_type_Private room in cabin",
                "property_type_Private room in camper/rv",
                "property_type_Private room in campsite",
                "property_type_Private room in casa particular",
                "property_type_Private room in castle",
                "property_type_Private room in cave",
                "property_type_Private room in chalet",
                "property_type_Private room in condominium",
                "property_type_Private room in cottage",
                "property_type_Private room in dome house",
                "property_type_Private room in earth house",
                "property_type_Private room in farm stay",
                "property_type_Private room in guest suite",
                "property_type_Private room in guesthouse",
                "property_type_Private room in hostel",
                "property_type_Private room in house",
                "property_type_Private room in hut",
                "property_type_Private room in kezhan",
                "property_type_Private room in loft",
                "property_type_Private room in minsu",
                "property_type_Private room in nature lodge",
                "property_type_Private room in resort",
                "property_type_Private room in ryokan",
                "property_type_Private room in serviced apartment",
                "property_type_Private room in tent",
                "property_type_Private room in tiny house",
                "property_type_Private room in townhouse",
                "property_type_Private room in treehouse",
                "property_type_Private room in villa",
                "property_type_Room in aparthotel",
                "property_type_Room in boutique hotel",
                "property_type_Room in heritage hotel",
                "property_type_Room in hotel",
                "property_type_Shared room",
                "property_type_Shared room in apartment",
                "property_type_Shared room in bed and breakfast",
                "property_type_Shared room in boutique hotel",
                "property_type_Shared room in bungalow",
                "property_type_Shared room in condominium",
                "property_type_Shared room in cottage",
                "property_type_Shared room in earth house",
                "property_type_Shared room in farm stay",
                "property_type_Shared room in guest suite",
                "property_type_Shared room in guesthouse",
                "property_type_Shared room in hostel",
                "property_type_Shared room in house",
                "property_type_Shared room in hut",
                "property_type_Shared room in kezhan",
                "property_type_Shared room in loft",
                "property_type_Shared room in nature lodge",
                "property_type_Shared room in serviced apartment",
                "property_type_Shared room in tent",
                "property_type_Shared room in tiny house",
                "property_type_Shared room in townhouse",
                "property_type_Shared room in villa",
                "property_type_Tent",
                "property_type_Tiny house",
                "property_type_Treehouse",
                "property_type_Yurt",
                "room_type_Entire home/apt",
                "room_type_Private room",
                "room_type_Shared room",
                "instant_bookable_t",
                "instant_bookable_f",
                "neighbourhood_cleansed_昌平区",
                "neighbourhood_cleansed_朝阳区 / Chaoyang",
                "neighbourhood_cleansed_大兴区 / Daxing",
                "neighbourhood_cleansed_东城区",
                "neighbourhood_cleansed_房山区",
                "neighbourhood_cleansed_丰台区 / Fengtai",
                "neighbourhood_cleansed_海淀区",
                "neighbourhood_cleansed_怀柔区 / Huairou",
                "neighbourhood_cleansed_门头沟区 / Mentougou",
                "neighbourhood_cleansed_密云县 / Miyun",
                "neighbourhood_cleansed_平谷区 / Pinggu",
                "neighbourhood_cleansed_石景山区",
                "neighbourhood_cleansed_顺义区 / Shunyi",
                "neighbourhood_cleansed_通州区 / Tongzhou",
                "neighbourhood_cleansed_西城区",
                "neighbourhood_cleansed_延庆县 / Yanqing",]
Y_name=["price"]

#选择X和Y的数据，并去除有缺失值的样本
XY_data=listing_data2[["host_time",
                #"first_review_to_today",
                #"last_review_to_today",
                "num_of_host_verifications",
                "num_of_amenities",
                "latitude",
                "longitude",
                "host_response_rate",
                "host_acceptance_rate",
                "host_listings_count",
                "accommodates",
                "bathrooms",
                "bedrooms",
                "beds",
                "minimum_nights",
                "maximum_nights",
                "availability_30",
                "availability_60",
                "availability_90",
                "availability_365",
                "number_of_reviews",
                "number_of_reviews_ltm",
                #"review_scores_rating",
                #"review_scores_accuracy",
                #"review_scores_cleanliness",
                #"review_scores_checkin",
                #"review_scores_communication",
                #"review_scores_location",
                #"review_scores_value",
                "calculated_host_listings_count",
                "calculated_host_listings_count_entire_homes",
                "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms",
                #"reviews_per_month",
                "host_response_time_a few days or more",
                "host_response_time_within a day",
                "host_response_time_within a few hours",
                "host_response_time_within an hour",
                "host_is_superhost_t",
                "host_is_superhost_f",
                "host_has_profile_pic_t",
                "host_has_profile_pic_f",
                "host_identity_verified_t",
                "host_identity_verified_f",
                "property_type_Barn",
                "property_type_Camper/RV",
                "property_type_Campsite",
                "property_type_Casa particular",
                "property_type_Castle",
                "property_type_Cave",
                "property_type_Dome house",
                "property_type_Earth house",
                "property_type_Entire apartment",
                "property_type_Entire bed and breakfast",
                "property_type_Entire bungalow",
                "property_type_Entire cabin",
                "property_type_Entire chalet",
                "property_type_Entire condominium",
                "property_type_Entire cottage",
                "property_type_Entire guest suite",
                "property_type_Entire guesthouse",
                "property_type_Entire home/apt",
                "property_type_Entire house",
                "property_type_Entire loft",
                "property_type_Entire place",
                "property_type_Entire resort",
                "property_type_Entire serviced apartment",
                "property_type_Entire townhouse",
                "property_type_Entire villa",
                "property_type_Farm stay",
                "property_type_Houseboat",
                "property_type_Hut",
                "property_type_Igloo",
                "property_type_Kezhan",
                "property_type_Minsu",
                "property_type_Pension",
                "property_type_Private room",
                "property_type_Private room in apartment",
                "property_type_Private room in barn",
                "property_type_Private room in bed and breakfast",
                "property_type_Private room in bungalow",
                "property_type_Private room in cabin",
                "property_type_Private room in camper/rv",
                "property_type_Private room in campsite",
                "property_type_Private room in casa particular",
                "property_type_Private room in castle",
                "property_type_Private room in cave",
                "property_type_Private room in chalet",
                "property_type_Private room in condominium",
                "property_type_Private room in cottage",
                "property_type_Private room in dome house",
                "property_type_Private room in earth house",
                "property_type_Private room in farm stay",
                "property_type_Private room in guest suite",
                "property_type_Private room in guesthouse",
                "property_type_Private room in hostel",
                "property_type_Private room in house",
                "property_type_Private room in hut",
                "property_type_Private room in kezhan",
                "property_type_Private room in loft",
                "property_type_Private room in minsu",
                "property_type_Private room in nature lodge",
                "property_type_Private room in resort",
                "property_type_Private room in ryokan",
                "property_type_Private room in serviced apartment",
                "property_type_Private room in tent",
                "property_type_Private room in tiny house",
                "property_type_Private room in townhouse",
                "property_type_Private room in treehouse",
                "property_type_Private room in villa",
                "property_type_Room in aparthotel",
                "property_type_Room in boutique hotel",
                "property_type_Room in heritage hotel",
                "property_type_Room in hotel",
                "property_type_Shared room",
                "property_type_Shared room in apartment",
                "property_type_Shared room in bed and breakfast",
                "property_type_Shared room in boutique hotel",
                "property_type_Shared room in bungalow",
                "property_type_Shared room in condominium",
                "property_type_Shared room in cottage",
                "property_type_Shared room in earth house",
                "property_type_Shared room in farm stay",
                "property_type_Shared room in guest suite",
                "property_type_Shared room in guesthouse",
                "property_type_Shared room in hostel",
                "property_type_Shared room in house",
                "property_type_Shared room in hut",
                "property_type_Shared room in kezhan",
                "property_type_Shared room in loft",
                "property_type_Shared room in nature lodge",
                "property_type_Shared room in serviced apartment",
                "property_type_Shared room in tent",
                "property_type_Shared room in tiny house",
                "property_type_Shared room in townhouse",
                "property_type_Shared room in villa",
                "property_type_Tent",
                "property_type_Tiny house",
                "property_type_Treehouse",
                "property_type_Yurt",
                "room_type_Entire home/apt",
                "room_type_Private room",
                "room_type_Shared room",
                "instant_bookable_t",
                "instant_bookable_f",
                "neighbourhood_cleansed_昌平区",
                "neighbourhood_cleansed_朝阳区 / Chaoyang",
                "neighbourhood_cleansed_大兴区 / Daxing",
                "neighbourhood_cleansed_东城区",
                "neighbourhood_cleansed_房山区",
                "neighbourhood_cleansed_丰台区 / Fengtai",
                "neighbourhood_cleansed_海淀区",
                "neighbourhood_cleansed_怀柔区 / Huairou",
                "neighbourhood_cleansed_门头沟区 / Mentougou",
                "neighbourhood_cleansed_密云县 / Miyun",
                "neighbourhood_cleansed_平谷区 / Pinggu",
                "neighbourhood_cleansed_石景山区",
                "neighbourhood_cleansed_顺义区 / Shunyi",
                "neighbourhood_cleansed_通州区 / Tongzhou",
                "neighbourhood_cleansed_西城区",
                "neighbourhood_cleansed_延庆县 / Yanqing",
                "price",]]
dropna_data=XY_data.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

#定义自变量
X=dropna_data[["host_time",
                #"first_review_to_today",
                #"last_review_to_today",
                "num_of_host_verifications",
                "num_of_amenities",
                "latitude",
                "longitude",
                "host_response_rate",
                "host_acceptance_rate",
                "host_listings_count",
                "accommodates",
                "bathrooms",
                "bedrooms",
                "beds",
                "minimum_nights",
                "maximum_nights",
                "availability_30",
                "availability_60",
                "availability_90",
                "availability_365",
                "number_of_reviews",
                "number_of_reviews_ltm",
                #"review_scores_rating",
                #"review_scores_accuracy",
                #"review_scores_cleanliness",
                #"review_scores_checkin",
                #"review_scores_communication",
                #"review_scores_location",
                #"review_scores_value",
                "calculated_host_listings_count",
                "calculated_host_listings_count_entire_homes",
                "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms",
                #"reviews_per_month",
                "host_response_time_a few days or more",
                "host_response_time_within a day",
                "host_response_time_within a few hours",
                "host_response_time_within an hour",
                "host_is_superhost_t",
                "host_is_superhost_f",
                "host_has_profile_pic_t",
                "host_has_profile_pic_f",
                "host_identity_verified_t",
                "host_identity_verified_f",
                "property_type_Barn",
                "property_type_Camper/RV",
                "property_type_Campsite",
                "property_type_Casa particular",
                "property_type_Castle",
                "property_type_Cave",
                "property_type_Dome house",
                "property_type_Earth house",
                "property_type_Entire apartment",
                "property_type_Entire bed and breakfast",
                "property_type_Entire bungalow",
                "property_type_Entire cabin",
                "property_type_Entire chalet",
                "property_type_Entire condominium",
                "property_type_Entire cottage",
                "property_type_Entire guest suite",
                "property_type_Entire guesthouse",
                "property_type_Entire home/apt",
                "property_type_Entire house",
                "property_type_Entire loft",
                "property_type_Entire place",
                "property_type_Entire resort",
                "property_type_Entire serviced apartment",
                "property_type_Entire townhouse",
                "property_type_Entire villa",
                "property_type_Farm stay",
                "property_type_Houseboat",
                "property_type_Hut",
                "property_type_Igloo",
                "property_type_Kezhan",
                "property_type_Minsu",
                "property_type_Pension",
                "property_type_Private room",
                "property_type_Private room in apartment",
                "property_type_Private room in barn",
                "property_type_Private room in bed and breakfast",
                "property_type_Private room in bungalow",
                "property_type_Private room in cabin",
                "property_type_Private room in camper/rv",
                "property_type_Private room in campsite",
                "property_type_Private room in casa particular",
                "property_type_Private room in castle",
                "property_type_Private room in cave",
                "property_type_Private room in chalet",
                "property_type_Private room in condominium",
                "property_type_Private room in cottage",
                "property_type_Private room in dome house",
                "property_type_Private room in earth house",
                "property_type_Private room in farm stay",
                "property_type_Private room in guest suite",
                "property_type_Private room in guesthouse",
                "property_type_Private room in hostel",
                "property_type_Private room in house",
                "property_type_Private room in hut",
                "property_type_Private room in kezhan",
                "property_type_Private room in loft",
                "property_type_Private room in minsu",
                "property_type_Private room in nature lodge",
                "property_type_Private room in resort",
                "property_type_Private room in ryokan",
                "property_type_Private room in serviced apartment",
                "property_type_Private room in tent",
                "property_type_Private room in tiny house",
                "property_type_Private room in townhouse",
                "property_type_Private room in treehouse",
                "property_type_Private room in villa",
                "property_type_Room in aparthotel",
                "property_type_Room in boutique hotel",
                "property_type_Room in heritage hotel",
                "property_type_Room in hotel",
                "property_type_Shared room",
                "property_type_Shared room in apartment",
                "property_type_Shared room in bed and breakfast",
                "property_type_Shared room in boutique hotel",
                "property_type_Shared room in bungalow",
                "property_type_Shared room in condominium",
                "property_type_Shared room in cottage",
                "property_type_Shared room in earth house",
                "property_type_Shared room in farm stay",
                "property_type_Shared room in guest suite",
                "property_type_Shared room in guesthouse",
                "property_type_Shared room in hostel",
                "property_type_Shared room in house",
                "property_type_Shared room in hut",
                "property_type_Shared room in kezhan",
                "property_type_Shared room in loft",
                "property_type_Shared room in nature lodge",
                "property_type_Shared room in serviced apartment",
                "property_type_Shared room in tent",
                "property_type_Shared room in tiny house",
                "property_type_Shared room in townhouse",
                "property_type_Shared room in villa",
                "property_type_Tent",
                "property_type_Tiny house",
                "property_type_Treehouse",
                "property_type_Yurt",
                "room_type_Entire home/apt",
                "room_type_Private room",
                "room_type_Shared room",
                "instant_bookable_t",
                "instant_bookable_f",
                "neighbourhood_cleansed_昌平区",
                "neighbourhood_cleansed_朝阳区 / Chaoyang",
                "neighbourhood_cleansed_大兴区 / Daxing",
                "neighbourhood_cleansed_东城区",
                "neighbourhood_cleansed_房山区",
                "neighbourhood_cleansed_丰台区 / Fengtai",
                "neighbourhood_cleansed_海淀区",
                "neighbourhood_cleansed_怀柔区 / Huairou",
                "neighbourhood_cleansed_门头沟区 / Mentougou",
                "neighbourhood_cleansed_密云县 / Miyun",
                "neighbourhood_cleansed_平谷区 / Pinggu",
                "neighbourhood_cleansed_石景山区",
                "neighbourhood_cleansed_顺义区 / Shunyi",
                "neighbourhood_cleansed_通州区 / Tongzhou",
                "neighbourhood_cleansed_西城区",
                "neighbourhood_cleansed_延庆县 / Yanqing",]].values
#定义标准化的自变量
xscaler=StandardScaler(copy=True, with_mean=True, with_std=True)
xscaler.fit(X)
XStandardlized=xscaler.transform(X)

#定义因变量：首先去除千分位分隔符，然后去掉$号
#Y=dropna_data["price"].str.replace(',', '')
#Y=Y.apply(lambda x : x[1:]).astype('float')
Y=dropna_data["price"]
#定义标准化的因变量
yscaler=StandardScaler(copy=True, with_mean=True, with_std=True)
yscaler.fit(pd.DataFrame(Y,columns=Y_name))
YStandardlized=yscaler.transform(pd.DataFrame(Y,columns=Y_name))
#最后才转化为array
Y=Y.values
YStandardlized=YStandardlized.reshape(-1,1)


#1.2.1
#线性回归statsmodels
#X0=sm.add_constant(X)
modelLR2=sm.OLS(Y,X).fit()
print("Linear Regression")
print(modelLR2.summary())
print("\n\n")

#1.2.2
#线性回归(Standardlized) statsmodels
#XStandardlized0=sm.add_constant(XStandardlized)
modelLRStandardlized2=sm.OLS(YStandardlized,XStandardlized).fit()
print("Linear Regression (Standardlized)")
print(modelLRStandardlized2.summary())
print("\n\n")

#2.1.2
#Ridge回归(Standardlized)
modelRidgeStandardlized=RidgeCV(alphas=[5525,1,0.1,0.5,0.005,0.01],fit_intercept=False, normalize=False, scoring=None, cv=5, gcv_mode=None, store_cv_values=False)
modelRidgeStandardlized.fit(XStandardlized,YStandardlized)
print("Ridge Regression (Standardlized)")
print("Alpha_\n{}".format(modelRidgeStandardlized.alpha_))
print("Score\n{}".format(modelRidgeStandardlized.score(XStandardlized,YStandardlized)))
print("Intercept\n{}".format(modelRidgeStandardlized.intercept_))
print("Coef")
for variable,coef in zip(X_names,modelRidgeStandardlized.coef_[0]):
    print("|{0:^50s}|{1:^30f}|".format(variable,coef))
print("\n\n")


#3.1.2
#Lasso回归(Standardlized)
modelLassoStandardlized=LassoCV(eps=1e-4, n_alphas=1000, alphas=None, fit_intercept=False, normalize=False, precompute='auto', max_iter=100000000, tol=1e-8, copy_X=True, cv=5, verbose=0, n_jobs=-1, positive=False, random_state=None, selection='cyclic')
modelLassoStandardlized.fit(XStandardlized,YStandardlized)
print("Lasso Regression (Standardlized)")
print("Alpha_\n{}".format(modelLassoStandardlized.alpha_))
print("Score\n{}".format(modelLassoStandardlized.score(XStandardlized,YStandardlized)))
print("Intercept\n{}".format(modelLassoStandardlized.intercept_))
print("Coef")
for variable,coef in zip(X_names,modelLassoStandardlized.coef_):
    print("|{0:^50s}|{1:^30f}|".format(variable,coef))
print("\n\n")