#房源推荐算法——基于 Airbnb 北京房价预测的机器学习模型
#第14组
#by 何智钧

#XGB
#2020-12-31
#聚类1

#导入第三方库
import pandas as pd
from sklearn.preprocessing import StandardScaler
from xgboost.sklearn import XGBRegressor
from xgboost import plot_importance, plot_tree
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt
from sklearn.inspection import plot_partial_dependence

#读取listing.csv并简要查看文件内容
listing_data1=pd.read_excel("E:/钧资料3/大学资料/课程/LN3125数据挖掘与机器学习/final project/beijing1026/listings/listings_clusters1211.xlsx",sheet_name="聚类1",header=0,names=None,verbose=True,engine="openpyxl")
print(listing_data1)
print(listing_data1.describe())
print(listing_data1.info())
print(listing_data1.dtypes)
print(listing_data1.shape)
for label in listing_data1.columns:
    print(label)
    #print(listing_data1[[label]].head(5))
    #print("Missing values: {}".format(listing_data1[[label]].isnull().sum()))
    #print("\n\n")

#定义自变量和因变量的名字
X_names=["host_time",
                #"first_review_to_today",
                #"last_review_to_today",
                "num_of_host_verifications",
                "num_of_amenities",
                "latitude",
                "longitude",
                "host_response_rate",
                "host_acceptance_rate",
                "host_listings_count",
                "accommodates",
                "bathrooms",
                "bedrooms",
                "beds",
                "minimum_nights",
                "maximum_nights",
                "availability_30",
                "availability_60",
                "availability_90",
                "availability_365",
                "number_of_reviews",
                "number_of_reviews_ltm",
                #"review_scores_rating",
                #"review_scores_accuracy",
                #"review_scores_cleanliness",
                #"review_scores_checkin",
                #"review_scores_communication",
                #"review_scores_location",
                #"review_scores_value",
                "calculated_host_listings_count",
                "calculated_host_listings_count_entire_homes",
                "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms",
                #"reviews_per_month",
                "host_response_time_a few days or more",
                "host_response_time_within a day",
                "host_response_time_within a few hours",
                "host_response_time_within an hour",
                "host_is_superhost_t",
                "host_is_superhost_f",
                "host_has_profile_pic_t",
                "host_has_profile_pic_f",
                "host_identity_verified_t",
                "host_identity_verified_f",
                "property_type_Barn",
                "property_type_Camper/RV",
                "property_type_Campsite",
                "property_type_Casa particular",
                "property_type_Castle",
                "property_type_Cave",
                "property_type_Dome house",
                "property_type_Earth house",
                "property_type_Entire apartment",
                "property_type_Entire bed and breakfast",
                "property_type_Entire bungalow",
                "property_type_Entire cabin",
                "property_type_Entire chalet",
                "property_type_Entire condominium",
                "property_type_Entire cottage",
                "property_type_Entire guest suite",
                "property_type_Entire guesthouse",
                "property_type_Entire home/apt",
                "property_type_Entire house",
                "property_type_Entire loft",
                "property_type_Entire place",
                "property_type_Entire resort",
                "property_type_Entire serviced apartment",
                "property_type_Entire townhouse",
                "property_type_Entire villa",
                "property_type_Farm stay",
                "property_type_Houseboat",
                "property_type_Hut",
                "property_type_Igloo",
                "property_type_Kezhan",
                "property_type_Minsu",
                "property_type_Pension",
                "property_type_Private room",
                "property_type_Private room in apartment",
                "property_type_Private room in barn",
                "property_type_Private room in bed and breakfast",
                "property_type_Private room in bungalow",
                "property_type_Private room in cabin",
                "property_type_Private room in camper/rv",
                "property_type_Private room in campsite",
                "property_type_Private room in casa particular",
                "property_type_Private room in castle",
                "property_type_Private room in cave",
                "property_type_Private room in chalet",
                "property_type_Private room in condominium",
                "property_type_Private room in cottage",
                "property_type_Private room in dome house",
                "property_type_Private room in earth house",
                "property_type_Private room in farm stay",
                "property_type_Private room in guest suite",
                "property_type_Private room in guesthouse",
                "property_type_Private room in hostel",
                "property_type_Private room in house",
                "property_type_Private room in hut",
                "property_type_Private room in kezhan",
                "property_type_Private room in loft",
                "property_type_Private room in minsu",
                "property_type_Private room in nature lodge",
                "property_type_Private room in resort",
                "property_type_Private room in ryokan",
                "property_type_Private room in serviced apartment",
                "property_type_Private room in tent",
                "property_type_Private room in tiny house",
                "property_type_Private room in townhouse",
                "property_type_Private room in treehouse",
                "property_type_Private room in villa",
                "property_type_Room in aparthotel",
                "property_type_Room in boutique hotel",
                "property_type_Room in heritage hotel",
                "property_type_Room in hotel",
                "property_type_Shared room",
                "property_type_Shared room in apartment",
                "property_type_Shared room in bed and breakfast",
                "property_type_Shared room in boutique hotel",
                "property_type_Shared room in bungalow",
                "property_type_Shared room in condominium",
                "property_type_Shared room in cottage",
                "property_type_Shared room in earth house",
                "property_type_Shared room in farm stay",
                "property_type_Shared room in guest suite",
                "property_type_Shared room in guesthouse",
                "property_type_Shared room in hostel",
                "property_type_Shared room in house",
                "property_type_Shared room in hut",
                "property_type_Shared room in kezhan",
                "property_type_Shared room in loft",
                "property_type_Shared room in nature lodge",
                "property_type_Shared room in serviced apartment",
                "property_type_Shared room in tent",
                "property_type_Shared room in tiny house",
                "property_type_Shared room in townhouse",
                "property_type_Shared room in villa",
                "property_type_Tent",
                "property_type_Tiny house",
                "property_type_Treehouse",
                "property_type_Yurt",
                "room_type_Entire home/apt",
                "room_type_Private room",
                "room_type_Shared room",
                "instant_bookable_t",
                "instant_bookable_f",
                "neighbourhood_cleansed_昌平区",
                "neighbourhood_cleansed_朝阳区 / Chaoyang",
                "neighbourhood_cleansed_大兴区 / Daxing",
                "neighbourhood_cleansed_东城区",
                "neighbourhood_cleansed_房山区",
                "neighbourhood_cleansed_丰台区 / Fengtai",
                "neighbourhood_cleansed_海淀区",
                "neighbourhood_cleansed_怀柔区 / Huairou",
                "neighbourhood_cleansed_门头沟区 / Mentougou",
                "neighbourhood_cleansed_密云县 / Miyun",
                "neighbourhood_cleansed_平谷区 / Pinggu",
                "neighbourhood_cleansed_石景山区",
                "neighbourhood_cleansed_顺义区 / Shunyi",
                "neighbourhood_cleansed_通州区 / Tongzhou",
                "neighbourhood_cleansed_西城区",
                "neighbourhood_cleansed_延庆县 / Yanqing",]
Y_name=["price"]

#选择X和Y的数据，并去除有缺失值的样本
XY_data=listing_data1[["host_time",
                #"first_review_to_today",
                #"last_review_to_today",
                "num_of_host_verifications",
                "num_of_amenities",
                "latitude",
                "longitude",
                "host_response_rate",
                "host_acceptance_rate",
                "host_listings_count",
                "accommodates",
                "bathrooms",
                "bedrooms",
                "beds",
                "minimum_nights",
                "maximum_nights",
                "availability_30",
                "availability_60",
                "availability_90",
                "availability_365",
                "number_of_reviews",
                "number_of_reviews_ltm",
                #"review_scores_rating",
                #"review_scores_accuracy",
                #"review_scores_cleanliness",
                #"review_scores_checkin",
                #"review_scores_communication",
                #"review_scores_location",
                #"review_scores_value",
                "calculated_host_listings_count",
                "calculated_host_listings_count_entire_homes",
                "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms",
                #"reviews_per_month",
                "host_response_time_a few days or more",
                "host_response_time_within a day",
                "host_response_time_within a few hours",
                "host_response_time_within an hour",
                "host_is_superhost_t",
                "host_is_superhost_f",
                "host_has_profile_pic_t",
                "host_has_profile_pic_f",
                "host_identity_verified_t",
                "host_identity_verified_f",
                "property_type_Barn",
                "property_type_Camper/RV",
                "property_type_Campsite",
                "property_type_Casa particular",
                "property_type_Castle",
                "property_type_Cave",
                "property_type_Dome house",
                "property_type_Earth house",
                "property_type_Entire apartment",
                "property_type_Entire bed and breakfast",
                "property_type_Entire bungalow",
                "property_type_Entire cabin",
                "property_type_Entire chalet",
                "property_type_Entire condominium",
                "property_type_Entire cottage",
                "property_type_Entire guest suite",
                "property_type_Entire guesthouse",
                "property_type_Entire home/apt",
                "property_type_Entire house",
                "property_type_Entire loft",
                "property_type_Entire place",
                "property_type_Entire resort",
                "property_type_Entire serviced apartment",
                "property_type_Entire townhouse",
                "property_type_Entire villa",
                "property_type_Farm stay",
                "property_type_Houseboat",
                "property_type_Hut",
                "property_type_Igloo",
                "property_type_Kezhan",
                "property_type_Minsu",
                "property_type_Pension",
                "property_type_Private room",
                "property_type_Private room in apartment",
                "property_type_Private room in barn",
                "property_type_Private room in bed and breakfast",
                "property_type_Private room in bungalow",
                "property_type_Private room in cabin",
                "property_type_Private room in camper/rv",
                "property_type_Private room in campsite",
                "property_type_Private room in casa particular",
                "property_type_Private room in castle",
                "property_type_Private room in cave",
                "property_type_Private room in chalet",
                "property_type_Private room in condominium",
                "property_type_Private room in cottage",
                "property_type_Private room in dome house",
                "property_type_Private room in earth house",
                "property_type_Private room in farm stay",
                "property_type_Private room in guest suite",
                "property_type_Private room in guesthouse",
                "property_type_Private room in hostel",
                "property_type_Private room in house",
                "property_type_Private room in hut",
                "property_type_Private room in kezhan",
                "property_type_Private room in loft",
                "property_type_Private room in minsu",
                "property_type_Private room in nature lodge",
                "property_type_Private room in resort",
                "property_type_Private room in ryokan",
                "property_type_Private room in serviced apartment",
                "property_type_Private room in tent",
                "property_type_Private room in tiny house",
                "property_type_Private room in townhouse",
                "property_type_Private room in treehouse",
                "property_type_Private room in villa",
                "property_type_Room in aparthotel",
                "property_type_Room in boutique hotel",
                "property_type_Room in heritage hotel",
                "property_type_Room in hotel",
                "property_type_Shared room",
                "property_type_Shared room in apartment",
                "property_type_Shared room in bed and breakfast",
                "property_type_Shared room in boutique hotel",
                "property_type_Shared room in bungalow",
                "property_type_Shared room in condominium",
                "property_type_Shared room in cottage",
                "property_type_Shared room in earth house",
                "property_type_Shared room in farm stay",
                "property_type_Shared room in guest suite",
                "property_type_Shared room in guesthouse",
                "property_type_Shared room in hostel",
                "property_type_Shared room in house",
                "property_type_Shared room in hut",
                "property_type_Shared room in kezhan",
                "property_type_Shared room in loft",
                "property_type_Shared room in nature lodge",
                "property_type_Shared room in serviced apartment",
                "property_type_Shared room in tent",
                "property_type_Shared room in tiny house",
                "property_type_Shared room in townhouse",
                "property_type_Shared room in villa",
                "property_type_Tent",
                "property_type_Tiny house",
                "property_type_Treehouse",
                "property_type_Yurt",
                "room_type_Entire home/apt",
                "room_type_Private room",
                "room_type_Shared room",
                "instant_bookable_t",
                "instant_bookable_f",
                "neighbourhood_cleansed_昌平区",
                "neighbourhood_cleansed_朝阳区 / Chaoyang",
                "neighbourhood_cleansed_大兴区 / Daxing",
                "neighbourhood_cleansed_东城区",
                "neighbourhood_cleansed_房山区",
                "neighbourhood_cleansed_丰台区 / Fengtai",
                "neighbourhood_cleansed_海淀区",
                "neighbourhood_cleansed_怀柔区 / Huairou",
                "neighbourhood_cleansed_门头沟区 / Mentougou",
                "neighbourhood_cleansed_密云县 / Miyun",
                "neighbourhood_cleansed_平谷区 / Pinggu",
                "neighbourhood_cleansed_石景山区",
                "neighbourhood_cleansed_顺义区 / Shunyi",
                "neighbourhood_cleansed_通州区 / Tongzhou",
                "neighbourhood_cleansed_西城区",
                "neighbourhood_cleansed_延庆县 / Yanqing",
                "price",]]
dropna_data=XY_data.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

#定义自变量
X=dropna_data[["host_time",
                #"first_review_to_today",
                #"last_review_to_today",
                "num_of_host_verifications",
                "num_of_amenities",
                "latitude",
                "longitude",
                "host_response_rate",
                "host_acceptance_rate",
                "host_listings_count",
                "accommodates",
                "bathrooms",
                "bedrooms",
                "beds",
                "minimum_nights",
                "maximum_nights",
                "availability_30",
                "availability_60",
                "availability_90",
                "availability_365",
                "number_of_reviews",
                "number_of_reviews_ltm",
                #"review_scores_rating",
                #"review_scores_accuracy",
                #"review_scores_cleanliness",
                #"review_scores_checkin",
                #"review_scores_communication",
                #"review_scores_location",
                #"review_scores_value",
                "calculated_host_listings_count",
                "calculated_host_listings_count_entire_homes",
                "calculated_host_listings_count_private_rooms",
                "calculated_host_listings_count_shared_rooms",
                #"reviews_per_month",
                "host_response_time_a few days or more",
                "host_response_time_within a day",
                "host_response_time_within a few hours",
                "host_response_time_within an hour",
                "host_is_superhost_t",
                "host_is_superhost_f",
                "host_has_profile_pic_t",
                "host_has_profile_pic_f",
                "host_identity_verified_t",
                "host_identity_verified_f",
                "property_type_Barn",
                "property_type_Camper/RV",
                "property_type_Campsite",
                "property_type_Casa particular",
                "property_type_Castle",
                "property_type_Cave",
                "property_type_Dome house",
                "property_type_Earth house",
                "property_type_Entire apartment",
                "property_type_Entire bed and breakfast",
                "property_type_Entire bungalow",
                "property_type_Entire cabin",
                "property_type_Entire chalet",
                "property_type_Entire condominium",
                "property_type_Entire cottage",
                "property_type_Entire guest suite",
                "property_type_Entire guesthouse",
                "property_type_Entire home/apt",
                "property_type_Entire house",
                "property_type_Entire loft",
                "property_type_Entire place",
                "property_type_Entire resort",
                "property_type_Entire serviced apartment",
                "property_type_Entire townhouse",
                "property_type_Entire villa",
                "property_type_Farm stay",
                "property_type_Houseboat",
                "property_type_Hut",
                "property_type_Igloo",
                "property_type_Kezhan",
                "property_type_Minsu",
                "property_type_Pension",
                "property_type_Private room",
                "property_type_Private room in apartment",
                "property_type_Private room in barn",
                "property_type_Private room in bed and breakfast",
                "property_type_Private room in bungalow",
                "property_type_Private room in cabin",
                "property_type_Private room in camper/rv",
                "property_type_Private room in campsite",
                "property_type_Private room in casa particular",
                "property_type_Private room in castle",
                "property_type_Private room in cave",
                "property_type_Private room in chalet",
                "property_type_Private room in condominium",
                "property_type_Private room in cottage",
                "property_type_Private room in dome house",
                "property_type_Private room in earth house",
                "property_type_Private room in farm stay",
                "property_type_Private room in guest suite",
                "property_type_Private room in guesthouse",
                "property_type_Private room in hostel",
                "property_type_Private room in house",
                "property_type_Private room in hut",
                "property_type_Private room in kezhan",
                "property_type_Private room in loft",
                "property_type_Private room in minsu",
                "property_type_Private room in nature lodge",
                "property_type_Private room in resort",
                "property_type_Private room in ryokan",
                "property_type_Private room in serviced apartment",
                "property_type_Private room in tent",
                "property_type_Private room in tiny house",
                "property_type_Private room in townhouse",
                "property_type_Private room in treehouse",
                "property_type_Private room in villa",
                "property_type_Room in aparthotel",
                "property_type_Room in boutique hotel",
                "property_type_Room in heritage hotel",
                "property_type_Room in hotel",
                "property_type_Shared room",
                "property_type_Shared room in apartment",
                "property_type_Shared room in bed and breakfast",
                "property_type_Shared room in boutique hotel",
                "property_type_Shared room in bungalow",
                "property_type_Shared room in condominium",
                "property_type_Shared room in cottage",
                "property_type_Shared room in earth house",
                "property_type_Shared room in farm stay",
                "property_type_Shared room in guest suite",
                "property_type_Shared room in guesthouse",
                "property_type_Shared room in hostel",
                "property_type_Shared room in house",
                "property_type_Shared room in hut",
                "property_type_Shared room in kezhan",
                "property_type_Shared room in loft",
                "property_type_Shared room in nature lodge",
                "property_type_Shared room in serviced apartment",
                "property_type_Shared room in tent",
                "property_type_Shared room in tiny house",
                "property_type_Shared room in townhouse",
                "property_type_Shared room in villa",
                "property_type_Tent",
                "property_type_Tiny house",
                "property_type_Treehouse",
                "property_type_Yurt",
                "room_type_Entire home/apt",
                "room_type_Private room",
                "room_type_Shared room",
                "instant_bookable_t",
                "instant_bookable_f",
                "neighbourhood_cleansed_昌平区",
                "neighbourhood_cleansed_朝阳区 / Chaoyang",
                "neighbourhood_cleansed_大兴区 / Daxing",
                "neighbourhood_cleansed_东城区",
                "neighbourhood_cleansed_房山区",
                "neighbourhood_cleansed_丰台区 / Fengtai",
                "neighbourhood_cleansed_海淀区",
                "neighbourhood_cleansed_怀柔区 / Huairou",
                "neighbourhood_cleansed_门头沟区 / Mentougou",
                "neighbourhood_cleansed_密云县 / Miyun",
                "neighbourhood_cleansed_平谷区 / Pinggu",
                "neighbourhood_cleansed_石景山区",
                "neighbourhood_cleansed_顺义区 / Shunyi",
                "neighbourhood_cleansed_通州区 / Tongzhou",
                "neighbourhood_cleansed_西城区",
                "neighbourhood_cleansed_延庆县 / Yanqing",]].values
#定义标准化的自变量
#xscaler=StandardScaler(copy=True, with_mean=True, with_std=True)
#xscaler.fit(X)
#XStandardlized=xscaler.transform(X)

#定义因变量：首先去除千分位分隔符，然后去掉$号
#Y=dropna_data["price"].str.replace(',', '')
#Y=Y.apply(lambda x : x[1:]).astype('float')
Y=dropna_data["price"]
#定义标准化的因变量
#yscaler=StandardScaler(copy=True, with_mean=True, with_std=True)
#yscaler.fit(pd.DataFrame(Y,columns=Y_name))
#YStandardlized=yscaler.transform(pd.DataFrame(Y,columns=Y_name))
#最后才转化为array
Y=Y.values
#YStandardlized=YStandardlized.reshape(-1,1)

#交叉验证选取最佳参数
modelXGB=GridSearchCV(XGBRegressor(verbosity=1, min_split_loss=0, objective='reg:squarederror',booster='gbtree',nthread=-1,gpu_id=0),
                    param_grid={"max_depth":[5],"n_estimators":range(143,146),"num_parallel_tree":[1],"learning_rate":[rate/100 for rate in range(10,11)],"subsample":[ratio/10 for ratio in range(10,11)], "reg_alpha":[alpha/10 for alpha in range(0,2)], "reg_lambda":[beta/10 for beta in range(15,16)],"eval_metric":["rmse"],"tree_method":["gpu_hist"],"sampling_method":["uniform"]},
                    scoring=None,cv=5,n_jobs=8,verbose=3)
modelXGB.fit(X,Y)
print(modelXGB.best_params_)
print(modelXGB.best_score_)
best_model=modelXGB.best_estimator_
print("score\n{}".format(modelXGB.score(X,Y)))
print("feature_importances")
for variable,coef in zip(X_names,best_model.feature_importances_):
    print("|{0:^50s}|{1:^30f}|".format(variable,coef))

#导出重要性的CSV文件
importance_df=pd.concat([pd.DataFrame(X_names,columns=["Variables"]),pd.DataFrame(best_model.feature_importances_,columns=["Importance"])],axis=1)
importance_df.to_csv("E:/钧资料3/大学资料/课程/LN3125数据挖掘与机器学习/final project/beijing1026/XGB1231-1.csv",
                 sep=',', na_rep='',columns=None, header=True,index=False,encoding="ANSI")

#作图
#选择最重要的4个变量
result_list=list(zip(X_names,best_model.feature_importances_))
result_list.sort(key=lambda x : x[1], reverse=True)
features=[]
for index in range(0,4):
    features.append(result_list[index][0])
#设置字体
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
#图1：第1-2重要的变量
plot_partial_dependence(best_model, X, features[0:2], feature_names=features[0:2], target=None, response_method='auto', n_cols=2, grid_resolution=100, percentiles=(0, 1), method='auto', n_jobs=4, verbose=1, fig=None, line_kw={"c": "red"}, contour_kw=None)
fig1=plt.gcf()
fig1.suptitle("Cluster 1 with XGB Regressor-1")
fig1.savefig('E:/钧资料3/大学资料/课程/LN3125数据挖掘与机器学习/final project/beijing1026/XGB1231-1-1.png',dpi=300, facecolor='w', edgecolor='w',orientation='portrait', papertype=None, format=None,transparent=False, bbox_inches=None, pad_inches=0.1,metadata=None)
#图2：第3-4重要的变量
plot_partial_dependence(best_model, X, features[2:4], feature_names=features[2:4], target=None, response_method='auto', n_cols=2, grid_resolution=100, percentiles=(0, 1), method='auto', n_jobs=4, verbose=1, fig=None, line_kw={"c": "purple"}, contour_kw=None)
fig2=plt.gcf()
fig2.suptitle("Cluster 1 with XGB Regressor-2")
fig2.savefig('E:/钧资料3/大学资料/课程/LN3125数据挖掘与机器学习/final project/beijing1026/XGB1231-1-2.png',dpi=300, facecolor='w', edgecolor='w',orientation='portrait', papertype=None, format=None,transparent=False, bbox_inches=None, pad_inches=0.1,metadata=None)

#输出预测价格
predict_df=pd.concat([listing_data1[["Label"]],listing_data1[["id"]],listing_data1[["price"]],pd.DataFrame(modelXGB.predict(X),columns=["Predict"])],axis=1)
predict_df.to_csv("E:/钧资料3/大学资料/课程/LN3125数据挖掘与机器学习/final project/beijing1026/predict1226-1.csv",
                 sep=',', na_rep='',columns=None, header=True,index=False,encoding="ANSI")

#打印结果摘录
"""
{'eval_metric': 'rmse', 'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 145, 'num_parallel_tree': 1, 'reg_alpha': 0.0, 'reg_lambda': 1.5, 'sampling_method': 'uniform', 'subsample': 1.0, 'tree_method': 'gpu_hist'}
0.34554272700492383
score
0.8840634408734387
"""